// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJqirH51zN58ejUlgenUxz3RUJ61wGTWs',
    appId: '1:223208187460:web:d5b20be472c8a6fb253e11',
    messagingSenderId: '223208187460',
    projectId: 'sensoresp-e642d',
    authDomain: 'sensoresp-e642d.firebaseapp.com',
    databaseURL: 'https://sensoresp-e642d-default-rtdb.firebaseio.com',
    storageBucket: 'sensoresp-e642d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoRT1WwUaZee4PTzKa_cQLvVYNZxmqHUU',
    appId: '1:223208187460:android:4439b76fbfcc26b9253e11',
    messagingSenderId: '223208187460',
    projectId: 'sensoresp-e642d',
    databaseURL: 'https://sensoresp-e642d-default-rtdb.firebaseio.com',
    storageBucket: 'sensoresp-e642d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTXP2eNz6hqA7sUfPdsnAAGpYf1BH7s1Y',
    appId: '1:223208187460:ios:4af5efc854e9897c253e11',
    messagingSenderId: '223208187460',
    projectId: 'sensoresp-e642d',
    databaseURL: 'https://sensoresp-e642d-default-rtdb.firebaseio.com',
    storageBucket: 'sensoresp-e642d.appspot.com',
    iosClientId: '223208187460-kc2gkpi3hrvfhdn456hneos34jjsh1ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.sensor',
  );
}
